import { Geist, Geist_Mono } from 'next/font/google'
import Script from 'next/script'
import { SpeedInsights } from '@vercel/speed-insights/next'
import './globals.css'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] })

// SEO: metablend.app is the declared canonical (both domains serve the site;
// the canonical consolidates ranking signals onto the branded one). Metadata
// is English — the SSR shell and default UI language are English.
// Kept under 160 chars — Bing flags longer meta descriptions as an SEO error,
// which counts against new domains in its indexing-quality checks.
const DESCRIPTION =
  'Free weather app blending 16 forecast sources — ECMWF, GFS, ICON and more — ' +
  'into one consensus that learns which source to trust in your city.'

export const metadata = {
  metadataBase: new URL('https://metablend.app'),
  title: {
    default: 'MetaBlend — One Forecast from 16 Weather Sources',
    template: '%s · MetaBlend',
  },
  description: DESCRIPTION,
  applicationName: 'MetaBlend',
  category: 'weather',
  keywords: [
    'weather forecast', 'weather consensus', 'multi-source weather forecast',
    'accurate weather forecast', 'compare weather forecasts', 'weather model comparison',
    'ECMWF forecast', 'GFS forecast', 'ICON model', 'weather API accuracy',
    'rain radar', '7 day forecast', 'will it rain today', 'best weather app',
    'Wettervorhersage', 'prévisions météo', 'previsión del tiempo', 'previsioni meteo',
  ],
  alternates: { canonical: '/' },
  manifest: '/manifest.json',
  openGraph: {
    // og:image is generated by app/opengraph-image.js (no static asset needed).
    title: 'MetaBlend — One Forecast from 16 Weather Sources',
    description: DESCRIPTION,
    url: 'https://metablend.app',
    siteName: 'MetaBlend',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    // twitter:image is generated by app/twitter-image.js.
    card: 'summary_large_image',
    title: 'MetaBlend — One Forecast from 16 Weather Sources',
    description: DESCRIPTION,
  },
  appleWebApp: {
    capable: true,
    title: 'MetaBlend',
    statusBarStyle: 'black-translucent',
  },
  icons: {
    icon: [
      { url: '/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/apple-touch-icon.png',
  },
}

export const viewport = {
  themeColor: '#0e0e12',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* Theme is dark by default; apply the light cookie before first paint
            so opted-in users never see a dark flash. Runs synchronously. */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{if(/(?:^|; )metablend_theme=light/.test(document.cookie))document.documentElement.dataset.theme='light'}catch(e){}",
          }}
        />
        {/* Structured data so search engines understand what MetaBlend is */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'WebApplication',
              name: 'MetaBlend',
              url: 'https://metablend.app',
              description: DESCRIPTION,
              applicationCategory: 'Weather',
              operatingSystem: 'Any',
              browserRequirements: 'Requires JavaScript',
              isAccessibleForFree: true,
              offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
              featureList: [
                'Weighted consensus from 16 weather sources',
                'Self-learning per-city forecast (MetaBlend Local)',
                'Live weather source accuracy leaderboard',
                '7-day consensus forecast',
                'Live rain radar',
                'UV index, air quality and pollen',
                'Travel planner from 10 years of climate data',
              ],
              inLanguage: ['en', 'de', 'fr', 'es', 'it'],
            }),
          }}
        />
        {children}
        <Script
          defer
          data-domain="metablend.app"
          src="https://plausible.io/js/script.js"
        />
        <SpeedInsights />
      </body>
    </html>
  )
}
